# Generated by Django 3.1.3 on 2020-11-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=150)),
                ('Last_name', models.CharField(blank=True, max_length=150)),
                ('Username', models.CharField(max_length=150, unique=True)),
                ('Email_ID', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=150)),
                ('Confirm_password', models.CharField(max_length=150)),
            ],
        ),
    ]
