# Generated by Django 3.1.3 on 2020-11-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mohan1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('last_name', models.DecimalField(decimal_places=2, max_digits=10)),
                ('username', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.DecimalField(decimal_places=2, max_digits=10)),
                ('password', models.IntegerField()),
                ('lead_time', models.IntegerField()),
            ],
        ),
    ]
