# Generated by Django 3.1.3 on 2020-11-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201124_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='advertise',
        ),
        migrations.RemoveField(
            model_name='register',
            name='anti_deteriorat',
        ),
        migrations.RemoveField(
            model_name='register',
            name='lead_time',
        ),
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='time_period',
        ),
        migrations.RemoveField(
            model_name='register',
            name='transport',
        ),
        migrations.AddField(
            model_name='register',
            name='First_name',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='Last_name',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
