# Generated by Django 3.1.3 on 2020-11-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='additem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(blank=True, max_length=150)),
                ('Order_advertisment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Transportation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Anti_deteriorate_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Usable_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Lead_time', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
